### ISSUE TITLE
Stock return {}

### ISSUE THREAD

**Issue by leoSZN** [supthunder/premeStock#7]
![image](https://user-images.githubusercontent.com/30168748/31398410-69f6d77e-ae1b-11e7-9b8c-a1d7cd1fca60.png)

Please help, keep hit this error. while my IDs are {'170929':'Corduroy Work Pant','170930':'Daggers Pant'}

**Comment by Bleez103** [comment]
@LeoSZN are you running into the below issue when running masterstock.py y?

Traceback (most recent call last):
File "C:\Users****\premeStock\monitor.py", line 263, in 
main(sys.argv)
File "C:\Users****\premeStock\monitor.py", line 233, in main
restockCheck(ID, 1)
File "C:\Users****\premeStock\monitor.py", line 186, in restockCheck
if sizes.find('option') == None:
AttributeError: 'NoneType' object has no attribute 'find'
